python:
    - "3.6"
install:
    - pip install -e .
    - pip install pytest-cov codecov    # to enable code coverage reports
script:
    - pytest --cov=simdist tests    # points to the source dir
after_success:
    - codecov    # uploads a code coverage report to codecov.io after every build.
